// Code generated by Slice Machine. DO NOT EDIT.

import BlogPost2 from './BlogPost2';
import BlogPosts from './BlogPosts';

export {
	BlogPost2,
	BlogPosts,
};

export const components = {
	blog_post2: BlogPost2,
	blog_posts: BlogPosts,
};
